---
title: "Anchoring"
author: "FH"
date: "26/1/2022"
output: pdf_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
options(warn=-1)
```


```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(RColorBrewer)
library(tidytext)
library(ggrepel)

theme_set(theme_bw())
theme_update(text = element_text(size = 15))

colors <- brewer.pal(n = 8, name = "Set2")
```

```{r}
pad <- "/home/frouke/Documents/Data/Anchoring/Calories/"
su_info <- read.csv(file.path(pad, "Demographics.csv"), 
                    stringsAsFactors = FALSE)
su_info %>% count(Gender)

labels <- su_info %>%
  dplyr::select(Name, Labels) %>%
  separate_rows(Labels, sep = ";")


```

```{r}
pad <- "/home/frouke/Documents/Data/Anchoring/Calories/"
guesses <- read.csv(file.path(pad, "Guesses.csv"), 
                    stringsAsFactors = FALSE) %>%
  mutate(Guess = as.numeric(gsub("\\\\", "", Guess))) %>%
  filter(!is.na(Guess)) %>%
  mutate(Image = gsub(".png", "", Image)) %>%
  mutate(Image = gsub(".jpg", "", Image))
  
design <- guesses %>% 
  distinct(Group, Cond, Image) %>% 
  mutate(Image = gsub(".png", "", Image)) %>%
  mutate(Image = gsub(".jpg", "", Image)) %>%
  spread(key = Group, value = Cond)

info <- guesses %>%
  distinct(Food, ActualKcal, Low, High) %>%
  dplyr::select(Food, ActualKcal, Low, High)

difference <- info %>%
  mutate(low_perc = 100*abs(Low-ActualKcal)/ActualKcal) %>%
  mutate(high_perc = 100*abs(High-ActualKcal)/ActualKcal) %>%
  mutate(low_rate = ActualKcal/Low) %>%
  mutate(high_rate = High/ActualKcal)
```

```{r}
ggplot(guesses, aes(x = Guess)) +
  geom_histogram(bins = 60, color = "black", fill = colors[1])
```

```{r}
av_guess <- guesses %>%
  filter(Guess < 1200) %>%
  group_by(Image, Cond) %>%
  summarise(mean = mean(Guess),
            se = sd(Guess)/sqrt(n()),
            n = n())

ggplot(av_guess, aes(x = Cond, y = mean)) +
  geom_bar(stat = "identity", color = "black", fill = colors[1]) +
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),
                width = 0.3) +
  facet_wrap(~Image, scales = "free") +
  coord_flip() +
  ylab("Estimate (kCal)") +
  xlab("")


guesses %>% filter(Image == "honey") %>% ggplot(aes(Guess)) +geom_histogram(color = "black", fill = colors[1]) + ggtitle("Guesses for honey") 
```

```{r}
foods <- unique(guesses$Image)

stats <- c()
for (food in foods)
{this_food <- guesses %>%
  filter(Image == food) %>%
  filter(!(Image == "honey" & Guess > 900)) %>%
  filter(Cond %in% c("Low", "High"))

res <- t.test(Guess ~ Cond, data = this_food, paired = FALSE)
stats <- bind_rows(stats, data.frame(food = food,
                            tstat = round(res$statistic, 3),
                            df = round(res$parameter, 1),
                            pval = round(res$p.value,3)))
}

stats <- arrange(stats, food)
```

```{r}
per_food <- guesses %>%
  filter(Guess < 1200) %>%
  filter(!(Image == "honey" & Guess > 900)) %>%
  filter(Cond == "Neutral") %>%
  group_by(Image) %>%
  summarise(mean_guess = mean(Guess),
            act_kcal = mean(ActualKcal)) %>%
  ungroup() %>%
  mutate(overestimation = mean_guess - act_kcal)

ggplot(per_food, aes(x = act_kcal, mean_guess)) +
  geom_point(color = colors[2], size = 3) +
  geom_abline(slope = 1, intercept = 0, color = colors[1]) +
  geom_text_repel(aes(label = Image)) +
  xlim(0, 450) +
  ylim(0, 450) +
  xlab("Actual kCal") +
  ylab("Estimated kCal")

cor.test(per_food$mean_guess, per_food$act_kcal)

cor.test(per_food$overestimation, per_food$act_kcal)

```

```{r}
all_data <- guesses %>%
  left_join(su_info) %>%
  filter(!is.na(Confidence)) %>%
  mutate(conf = case_when(Confidence == "Not at all confident" ~ "Not confident",
                          Confidence == "Not so confident" ~ "Not confident",
                          TRUE ~ "Confident")) %>%
  mutate(abs_err = abs(ActualKcal-Guess))

per_food_cond <- all_data %>%
  group_by(conf, Cond, Image) %>%
  summarise(mean = mean(abs_err),
            se = sd(abs_err)/sqrt(n()),
            n = n())


ggplot(per_food_cond, aes(x = Cond, y = mean, fill = conf)) +
  geom_bar(stat = "identity", color = "black",
           position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),
                width = 0.3, position = position_dodge(width = 0.9)) +
  facet_wrap(~Image, scales = "free") +
  coord_flip() +
  ylab("Estimate (kCal)") +
  xlab("")

per_food_cond <- all_data %>%
  group_by(conf, Cond, Image) %>%
  summarise(act = mean(ActualKcal),
            est = mean(Guess))

ggplot(per_food_cond, aes(x = act, y = est, color = conf, shape = conf)) +
  geom_point(size = 3) +
  geom_abline(slope = 1, intercept = 0) +
  geom_text_repel(aes(label = Image)) +
  facet_wrap(~Cond, nrow = 2) +
  xlim(0, 450) +
  ylim(0, 450) +
  xlab("Actual kCal") +
  ylab("Estimated kCal") +
  scale_color_manual(values = colors, name = "") +
  scale_shape_manual(values = c(16, 17), name = "") +
  theme(legend.position = "top")

```

```{r}

foods <- unique(all_data$Image)
conds <- unique(all_data$Cond)

stats <- c()
for (food in foods)
  for (cond in conds)
  {
{this_food <- all_data %>%
  filter(Image == food) %>%
  filter(Cond == cond) %>%
  filter(!(Image == "honey" & Guess > 900)) 

res <- t.test(abs_err ~ conf, data = this_food, paired = FALSE)
stats <- bind_rows(stats, data.frame(food = food,
                            cond = cond, 
                            tstat = round(res$statistic, 3),
                            df = round(res$parameter, 1),
                            pval = round(res$p.value,3)))
}
}

ggplot(stats, aes(y = food, x = cond)) +
  geom_tile(aes(fill = pval)) +
  geom_text(aes(label = paste0("p = ", round(pval, 2))), 
            size = 4, color = "white") +
  xlab("Anchoring condition") +
  ylab("") +
  theme(legend.position = "none")

```

```{r}
calo_conf <- all_data %>% mutate(calo = ifelse(grepl("Calories", Labels), "Checks calories", "Does not check calories")) %>% 
  distinct(calo, Name, conf) 

fisher.test(table(calo_conf$conf, calo_conf$calo))

counts <- calo_conf %>%
  count(conf, calo) %>%
  group_by(calo) %>%
  mutate(perc = 100*n/sum(n))

```

```{r}
all_data <- guesses %>%
  left_join(su_info) %>%
  filter(!is.na(Confidence)) %>%
  mutate(conf = case_when(Confidence == "Not at all confident" ~ "Not confident",
                          Confidence == "Not so confident" ~ "Not confident",
                          TRUE ~ "Confident")) %>%
  mutate(abs_err = abs(ActualKcal-Guess)) %>%
  mutate(calo = ifelse(grepl("Calories", Labels), "Checks calories", "Does not check calories"))


per_food_cond <- all_data %>%
  group_by(calo, Cond, Image) %>%
  summarise(act = mean(ActualKcal),
            est = mean(Guess))

ggplot(per_food_cond, aes(x = act, y = est, color = calo, shape = calo)) +
  geom_point(size = 3) +
  geom_abline(slope = 1, intercept = 0) +
  geom_text_repel(aes(label = Image)) +
  facet_wrap(~Cond, nrow = 2) +
  xlim(0, 450) +
  ylim(0, 450) +
  xlab("Actual kCal") +
  ylab("Estimated kCal") +
  scale_color_manual(values = colors, name = "") +
  scale_shape_manual(values = c(16, 17), name = "") +
  theme(legend.position = "top")


```

