# Thanks https://github.com/marketplace/actions/github-action-for-latex

name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: researchProposal-Yasin_Gul-Arjan_Broer.tex
          working_directory: proposal
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: proposal/researchProposal-Yasin_Gul-Arjan_Broer.pdf
